name: ms-grpc-manager
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=
  - colorama=
  - numpy=
  - pandas=
  - geopy=
  - pvlib-python=
  - urllib3=
  - beautifulsoup4=
  - matplotlib=
  - requests=
  - pydantic=
  - jsonpickle=
  - sqlalchemy=
  - psycopg2=
  - pytest=
  - pytest-env=
  - pytest-dotenv=
  - pytest-mock=
  - pip:
    - grpcio==1.44.0
    - protobuf==3.20.1
    - python-dotenv==0.20.0
