name: Create and Publish a Docker Image in GHCR

on:
  push:
    branches:
      - "qa"
#      - "main"
  pull_request:
    branches:
      - "qa"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  CTR_USER: ${{ secrets.CTR_USER }}
  CTR_TOKEN: ${{ secrets.CTR_TOKEN }}

jobs:
  build-and-push-image:
#    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to the Container Registry
        uses: docker/login-action@v2.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.NEW_CTR_USER }}
          password: ${{ env.NEW_CTR_TOKEN }}

      - name: Extract Metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.0.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Load submodules
        run: |
          git submodule init
          git submodule update

      - name: Build and Push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}